print("enter username")
usernmae=input()
print("your username is :", usernmae)
print("enter emailid")
emailid=input()
print('your emailid:', emailid)
print("enter DOB ")
DOB=input()
print('your DOB:', DOB)
print("enter Age ")
age=input()
print('your age:', age)
print("enter Fathername ")
Fname=input()
print('your fathername:', Fname)
print("enter mother name")
Mname=input()
print("your mothername",Mname)
print("enter mobileno ")
Mob=input()
print('your mobileno :', Mob)